(display "Hello,World!\n")

;; define a method,return the first two max num sum
(define (plus-first-two-num a b c)
  (if (> a b)
      (cond ((> b c) (+ a b))
	    ((> c b) (+ a c)))
      (cond ((> a c) (+ b a))
		  (else (+ b c)))))

(define a 3)
(define b 4)
(define c 5)
(define d (plus-first-two-num a b c))
(display "\n The a is:")
(display a)
(display "\n The b is:")
(display b)
(display "\n The c is:")
(display c)
(display "\n The result:")
(display  d)
(display "\n")
